In [3]:
#python vs numpy
l = range(1000000)

In [5]:
import numpy as np

In [7]:
d = np.arange(1000000)

In [6]:
%time for i in range(1,10):r = [x*2 for x in l]


Wall time: 832 ms


In [8]:
%time for i in range(1,10):r = d*2

Wall time: 40.8 ms


# ndarray

In [12]:
x = np.zeros((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.empty((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
l=[1,4,5,7]
x=np.array(l)

In [28]:
x = np.arange(1,100,10)
x.shape

(10,)

In [30]:
x = np.zeros((10,10))
x.shape

(10, 10)

In [42]:
y = x.reshape((2,2,5,5))
print(y)

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


In [44]:
y.dtype

dtype('float64')

In [45]:
d.ndim

1

In [50]:
#Arthimetic with ndarray
a = np.random.rand((10))
b = np.random.rand((10))


In [51]:
a + b

array([1.18441019, 0.80467527, 1.00832169, 1.55143956, 1.08194877,
       0.89726237, 0.71175089, 1.47188662, 1.83159943, 1.70915866])

In [52]:
a * b

array([0.3501623 , 0.15470127, 0.24738615, 0.56406058, 0.27809787,
       0.19205336, 0.08783501, 0.53970745, 0.83846919, 0.71608818])

In [53]:
a/b

array([0.92417645, 0.65217859, 0.71900026, 0.59969487, 0.63530186,
       1.54450009, 3.48016818, 1.12609486, 0.96812903, 0.75511256])

In [54]:
a-b

array([-0.04667253, -0.16940257, -0.16482728, -0.3882298 , -0.24129166,
        0.19200606,  0.39401688,  0.08729495, -0.02966008, -0.23847559])

In [65]:
2*a
1/a
2/a
a > 0.5
a [a>0.5]

array([0.56886883, 0.58160488, 0.54463422, 0.55288389, 0.77959078,
       0.90096968, 0.73534154])

# Indexing and Slicing

In [78]:
x = np.array([1,7,9,8,5])
x[4]

5

In [79]:
x[x>5] #ya boolean indexcing hai

array([7, 9, 8])

In [80]:
x[[2,1]] #ya fancy indexcing hai

array([9, 7])

In [82]:
x = np.random.rand(10,10)
x

array([[0.58595054, 0.46446335, 0.12101638, 0.33476236, 0.5218324 ,
        0.00754176, 0.43046826, 0.00943384, 0.80264449, 0.04605565],
       [0.61364618, 0.09742575, 0.7479989 , 0.82276819, 0.17462745,
        0.93663767, 0.82441892, 0.70092618, 0.96916907, 0.91397621],
       [0.16461406, 0.05082535, 0.22954642, 0.82843924, 0.20408148,
        0.14775743, 0.93532755, 0.21586337, 0.72286758, 0.30882474],
       [0.81424683, 0.39124564, 0.87282249, 0.7517098 , 0.14719681,
        0.46143164, 0.15967285, 0.7863183 , 0.54211742, 0.47616042],
       [0.11017651, 0.53564856, 0.44489237, 0.87216498, 0.3120494 ,
        0.62133844, 0.0473617 , 0.68985461, 0.94405168, 0.00516654],
       [0.25491074, 0.9307242 , 0.60561134, 0.80745059, 0.3206955 ,
        0.32880576, 0.0755359 , 0.05697157, 0.1766646 , 0.04757631],
       [0.79151877, 0.51702338, 0.15990404, 0.51202609, 0.07864642,
        0.1117204 , 0.90173774, 0.42581259, 0.78671868, 0.81708155],
       [0.33814487, 0.33728488, 0.3991083

In [83]:
x[0]

array([0.58595054, 0.46446335, 0.12101638, 0.33476236, 0.5218324 ,
       0.00754176, 0.43046826, 0.00943384, 0.80264449, 0.04605565])

In [85]:
x[0][4]

0.5218323997533179

In [86]:
x[1:10:2,::]

array([[0.61364618, 0.09742575, 0.7479989 , 0.82276819, 0.17462745,
        0.93663767, 0.82441892, 0.70092618, 0.96916907, 0.91397621],
       [0.81424683, 0.39124564, 0.87282249, 0.7517098 , 0.14719681,
        0.46143164, 0.15967285, 0.7863183 , 0.54211742, 0.47616042],
       [0.25491074, 0.9307242 , 0.60561134, 0.80745059, 0.3206955 ,
        0.32880576, 0.0755359 , 0.05697157, 0.1766646 , 0.04757631],
       [0.33814487, 0.33728488, 0.39910837, 0.56266363, 0.33585941,
        0.47718999, 0.17940048, 0.03857705, 0.37737367, 0.73956632],
       [0.06619415, 0.87504559, 0.97363541, 0.45380649, 0.66302457,
        0.54736161, 0.8929237 , 0.62312551, 0.6671283 , 0.0061086 ]])

In [28]:
g=np.ones((5,5))
g

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
g[1:-1,1:-1] = 0
g

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
x = np.array([9,15,6,30,50])

In [41]:
np.sqrt(x)

array([3.        , 3.87298335, 2.44948974, 5.47722558])

In [42]:
np.power(x,2)

array([ 81, 225,  36, 900], dtype=int32)

In [43]:
y = [7,1,2,6,4]

In [47]:
np.maximum(x,y)

array([ 9, 15,  6, 30, 50])

In [51]:
#Np.where
#Ternary Operator
salary =np.array([0,-1,100000,200000])


In [53]:
np.where(salary<= 0, 25000, salary)

array([ 25000,  25000, 100000, 200000])

In [54]:
np.where(salary<=0,"No Ok", "Ok")

array(['No Ok', 'No Ok', 'Ok', 'Ok'], dtype='<U5')

# Mathematical & Statistical Methods

In [55]:
x = np.array([10,9,8,7,6])

In [56]:
x.mean()

8.0

In [57]:
x.cumsum()

array([10, 19, 27, 34, 40], dtype=int32)

In [59]:
x.cumprod()

array([   10,    90,   720,  5040, 30240], dtype=int32)

In [60]:
y = x > 6
y

array([ True,  True,  True,  True, False])

In [62]:
y.sum()

4

In [63]:
y.any()

True

In [64]:
y.all()

False

In [66]:
y = x > 7 
y

array([ True,  True,  True, False, False])

In [67]:
y.sum()

3

In [68]:
y.any()

True

In [69]:
y.all()

False

In [70]:
x.sort()

In [71]:
x

array([ 6,  7,  8,  9, 10])

In [73]:
np.unique(x)

array([ 6,  7,  8,  9, 10])

# File Input Output

In [75]:
# To save multiple array use np.savez(filename, specify rest of the array element)
# it will return the dictonary

In [92]:
x = [7,5,6,8,9]
y = [6,8,6,2,0]

In [78]:
#to save x
np.save('textx',x)

In [83]:
loadx = np.load('textx.npy')
loadx

array([7, 5, 6, 8, 9])

In [113]:
np.savez('testxy',x = x,y = y)

In [114]:
loadzxy = np.load('testxy.npz')

In [115]:
loadzxy

In [117]:
loadzxy ['x']

array([7, 5, 6, 8, 9])

# Linear Algebra

In [119]:
x = np.random.randn(3,2)

In [120]:
y = np.random.rand(2,3)

In [121]:
x.dot(y)

array([[1.19542009, 0.86667333, 0.67046201],
       [1.91242788, 1.37097333, 1.06473378],
       [0.53560249, 0.72475281, 0.47089434]])

In [122]:
x.transpose()

array([[ 0.05074449,  0.00664492,  1.63781307],
       [ 1.51479061,  2.49330612, -0.83702774]])

In [123]:
x.trace()

2.5440506050297875

# Pseudo Random Number

In [128]:
x = np.random.seed(5)

In [130]:
np.random.normal(size=(3,3))

array([[ 0.44122749, -0.33087015,  2.43077119],
       [-0.25209213,  0.10960984,  1.58248112],
       [-0.9092324 , -0.59163666,  0.18760323]])

In [133]:
np.random.uniform(size = (3,4))

array([[0.26581912, 0.28468588, 0.25358821, 0.32756395],
       [0.1441643 , 0.16561286, 0.96393053, 0.96022672],
       [0.18841466, 0.02430656, 0.20455555, 0.69984361]])

In [134]:
x = np.arange(20)

In [135]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [151]:
np.shape(x)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [161]:
np.reshape(x, [-1,5] ,'F')

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [162]:
x = np.random.randn(4,5)

In [163]:
x

array([[-0.32986996,  2.23874294,  0.24778538,  0.32639613,  0.26650019],
       [ 0.37746398, -0.02392064,  1.22888408, -0.39583126,  1.52502591],
       [ 0.26157022, -0.4875009 , -0.01560054,  1.13366694,  0.47173221],
       [ 1.96863378,  0.96110296, -0.25369298, -0.74089058,  0.05206415]])

In [169]:
y = x.reshape((2,2,5))
y

array([[[-0.32986996,  2.23874294,  0.24778538,  0.32639613,
          0.26650019],
        [ 0.37746398, -0.02392064,  1.22888408, -0.39583126,
          1.52502591]],

       [[ 0.26157022, -0.4875009 , -0.01560054,  1.13366694,
          0.47173221],
        [ 1.96863378,  0.96110296, -0.25369298, -0.74089058,
          0.05206415]]])

In [170]:
np.shape(y)

(2, 2, 5)

In [171]:
np.ndim(y)

3

In [172]:
y.ravel()

array([-0.32986996,  2.23874294,  0.24778538,  0.32639613,  0.26650019,
        0.37746398, -0.02392064,  1.22888408, -0.39583126,  1.52502591,
        0.26157022, -0.4875009 , -0.01560054,  1.13366694,  0.47173221,
        1.96863378,  0.96110296, -0.25369298, -0.74089058,  0.05206415])

In [173]:
y.flatten()

array([-0.32986996,  2.23874294,  0.24778538,  0.32639613,  0.26650019,
        0.37746398, -0.02392064,  1.22888408, -0.39583126,  1.52502591,
        0.26157022, -0.4875009 , -0.01560054,  1.13366694,  0.47173221,
        1.96863378,  0.96110296, -0.25369298, -0.74089058,  0.05206415])

In [182]:
x = np.array([[1,1,1,],[1,1,1]])
x

array([[1, 1, 1],
       [1, 1, 1]])

In [183]:
y = np.array([[9,9,9,],[9,9,9]])
y

array([[9, 9, 9],
       [9, 9, 9]])

In [185]:
np.concatenate((x,y), axis = 1)

array([[1, 1, 1, 9, 9, 9],
       [1, 1, 1, 9, 9, 9]])

In [186]:
x = [[1,3,4],[6,7,8]]
y = [[10,11,12],[15,16,17]]
arr1 = np.array(x)
arr2 = np.array(y)

In [187]:
np.concatenate((arr1,arr2),axis = 0)

array([[ 1,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [15, 16, 17]])

In [188]:
np.concatenate((arr1,arr2),axis = 1)

array([[ 1,  3,  4, 10, 11, 12],
       [ 6,  7,  8, 15, 16, 17]])

In [190]:
np.vstack((arr1,arr2))

array([[ 1,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [15, 16, 17]])

In [191]:
np.hstack((arr1,arr2))

array([[ 1,  3,  4, 10, 11, 12],
       [ 6,  7,  8, 15, 16, 17]])

In [193]:
#SPlIT Completemtary method

In [195]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [196]:
np.array(x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [209]:
np.split(x,[2,6])

[array([0, 1]), array([2, 3, 4, 5]), array([6, 7, 8, 9])]

In [211]:
x = [[1,6,8,6,7],[6,9,8,7,5]]

In [218]:
a = np.array(x)
a

array([[1, 6, 8, 6, 7],
       [6, 9, 8, 7, 5]])

In [229]:
np.split(a,[1], axis = 0)

[array([[1, 6, 8, 6, 7]]), array([[6, 9, 8, 7, 5]])]

# Repeat & Tile

In [230]:
# Repeat
d = np.array([1,5,7,8])

In [231]:
np.repeat(d,2)

array([1, 1, 5, 5, 7, 7, 8, 8])

In [232]:
np.repeat(d,3, axis = 0)

array([1, 1, 1, 5, 5, 5, 7, 7, 7, 8, 8, 8])

In [235]:
a

array([[1, 6, 8, 6, 7],
       [6, 9, 8, 7, 5]])

In [236]:
np.repeat(a,2, axis = 1)

array([[1, 1, 6, 6, 8, 8, 6, 6, 7, 7],
       [6, 6, 9, 9, 8, 8, 7, 7, 5, 5]])

In [237]:
np.repeat(a,2, axis = 0)

array([[1, 6, 8, 6, 7],
       [1, 6, 8, 6, 7],
       [6, 9, 8, 7, 5],
       [6, 9, 8, 7, 5]])

In [238]:
d

array([1, 5, 7, 8])

In [241]:
np.tile(d,2)

array([1, 5, 7, 8, 1, 5, 7, 8])

In [242]:
a

array([[1, 6, 8, 6, 7],
       [6, 9, 8, 7, 5]])

In [245]:
np.tile(a,2)

array([[1, 6, 8, 6, 7, 1, 6, 8, 6, 7],
       [6, 9, 8, 7, 5, 6, 9, 8, 7, 5]])

In [251]:
np.repeat(a,2, axis = 0)

array([[1, 6, 8, 6, 7],
       [1, 6, 8, 6, 7],
       [6, 9, 8, 7, 5],
       [6, 9, 8, 7, 5]])